config/routes.rb
Rails.application.routes.draw do
devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'home#index' 
resources :notes
resources :books
 # Agregados para hacer el pase desde Book a Note
get 'books/:book_id/notes', to: 'notes#index_notes_of_book', as: 'notes_of_book'
get 'books/:book_id/notes/:note_id', to: 'notes#show'
get 'books/:book_id/note', to: 'notes#new_note_of_book', as: 'new_note_of_book'
get 'notes/:id/download', to: 'notes#download', as: 'download'
get 'books/:id/download', to: 'books#download', as: 'download_zip'
get 'download', to: 'books#download_all', as: 'download_all'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user, inverse_of: :notes
  belongs_to :book, optional: true, inverse_of: :notes

  validates :title, presence: true, length: { maximum: 255 }, format: { with: /\A(\w|(\w[\w\s]*\w))\z/, message: "no debe comenzar ni terminar con espacios en blanco"}
  validates :content, presence: true
  validates_uniqueness_of :title, scope: [:book_id,:user_id]
  
  def to_s
    title
  end

  def self.search(user, search, book=nil)
     if book== nil
       notes =  where("user_id == #{user} AND book_id is null")
     else
       notes =  where("user_id == #{user} AND book_id == #{book}")
     end
     notes =  notes.where("title like ? OR content like ?", "%#{search}%", "%#{search}%") if search
     notes
  end


  def show_content
      renderer = Redcarpet::Render::HTML.new(prettify: true)
      (Redcarpet::Markdown.new(renderer, fenced_code_blocks: true)).render(content)
  end

  def markdown
      renderer = Redcarpet::Render::HTML.new(prettify: true)
      (Redcarpet::Markdown.new(renderer, fenced_code_blocks: true)).render(content.insert(0,"###### #{created_at}\n# #{title}\n"))
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_note, only: [:show, :edit, :update, :destroy, :download]
    
    def index
        @notes = current_user.notes.search(current_user.id, params[:search]).paginate(page: params[:page], per_page: 5).order("created_at DESC")
    end
 
    def new
        @note = current_user.notes.new
    end
    
    def create
        @note = current_user.notes.create note_params
        if @note.errors.empty?
           redirect_to note_path?(@note), notice: "Se creo la nota '#{@note.title}'"
        end
    end
    
    def show
       @title = @note.title
       @content = @note.show_content
    end
    
    def edit
    end

    def update
        @note.update note_params
        if @note.errors.empty?
           redirect_to note_path?(@note), notice: "Se actualizo la nota '#{@note.title}'"
        end
    end
    
    def destroy
        @note.book_id.nil? ? p = notes_path : p = notes_of_book_path(@note.book_id)
        title = @note.title
        @note.destroy
        redirect_to p, notice: "La nota '#{ title }' se elimino exitosamente"
    end

    def download
        send_data(@note.markdown, filename:"#{@note.title}.html", type: "html", disposition: "attachment")
    end

    def index_notes_of_book
        if current_user.id == Book.find(params[:book_id]).user_id
          @notes = current_user.notes.search(current_user.id, params[:search], params[:book_id] ).paginate(page: params[:page], per_page: 5).order("created_at DESC")
        else
           redirect_to "#{root_path}403" 
        end
    end 
 
    def new_note_of_book
        @note = current_user.notes.new
        @note.book_id = params[:book_id]
    end

    private
    
    def note_params
        params.require(:note).permit(:title, :content, :book_id)
    end

    # uso de callback de before_action
    def set_note
        @note = current_user.notes.find(params[:id])
        if @note.nil?
           redirect_to "#{root_path}403"
        end
    end

    def note_path?(nota)
        nota.book_id.nil? ? p = notes_path : p = notes_of_book_path(nota.book_id)
    end

end

app/helpers/notes_helper.rb
module NotesHelper

end

app/views/notes/_codemirror.html.erb
<script>
 CodeMirror.fromTextArea(document.getElementById("form-note"), {
 theme: "defualt",
 mode: "markdown",
 lineNumbers: true,
 lineWrapping: true,
})
</script>

app/views/notes/_form.html.erb
<%= form_for @note, remote: true do |f| %>
    <%= f.hidden_field :book_id, value: @note.book_id %> 
    <%= f.label :titulo %>
    <%= f.text_field :title, class: "form-control input-lg", placeholder: "Nombre de la nota" %>
    <%= f.label :contenido %>
    <%= f.text_area :content, id: "form-note",  class: "codemirror-textarea form-control input-lg", placeholder: "Texto de la nota" %>
    <%= f.submit 'Enviar', class: "btn btn-primary" %>
    <%- if @note.book_id.nil? %>
        <%= link_to 'Cancelar', notes_path, class: 'btn btn-secundary' %>
    <% else %>
        <%= link_to 'Cancelar', notes_of_book_path(@note.book_id), class: 'btn btn-secundary' %>
    <% end %>
    <% end %>

app/views/notes/_note.html.erb
<tr id=<%= note.id %> >
<th scope="row"><%= link_to note.title, note_path(note) %></th>
<td><%= note.created_at.strftime("%d-%m-%Y   %H:%M") %></td>
<td><%= link_to '<i class="fas fa-download"></i>'.html_safe, download_path(note), target: "_blank" %></td>
<td><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_note_path(note) %></td>
<td><%= link_to '<i class="fas fa-trash"></i>'.html_safe, note, method: :delete, data: { confirm: 'Esta seguro?'} %></td>
</tr>

app/views/notes/create.js.erb
<% if @note.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('#tnote tbody').prepend(' <%= j render "note", note: @note %>');
  if($('#tnote tr').length > 7)
            {
                // Eliminamos la ultima columna
            $('#tnote tbody').find('tr:last').remove();

            };
  $('.alert').html("La nota ha sido creado con éxito").show();
  $('#form-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @note.errors.full_messages[0] %>');
<% end %>

app/views/notes/edit.html.erb
<h3><%= @note.title %> </h3>

<%= render 'form', note: @note %>

<%= render 'codemirror' %>

app/views/notes/index.html.erb
<div class="form-group" align='right'>
<form >
 <input name='search' <%= @search %> >
 <button type=”submit”><i class="fas fa-search"></i></button>
</form>
</div>
<h2>Lista de notas</h2>
<table class="table table-striped table-bordered" id="tnote">
  <thead>
  </thead>
  <tbody>
<%= render @notes %>
  </tbody>
</table>
<br />
<%= will_paginate @notes, class: "pagination page-link btn" %> <br />
<%= link_to 'Crear una nota', new_note_path,  class: 'btn btn-primary' %>

app/views/notes/index_notes_of_book.html.erb
<div class="form-group" align='right'>
<form >
 <input name='search' <%= @search %> >
 <button type=”submit”><i class="fas fa-search"></i></button>
</form>
</div>
<h2>Lista de notas para "<%= Book.find(params[:book_id]).title %>"</h2>
<table class="table table-striped table-bordered" id="tnote">
  <thead>
  </thead>
  <tbody>
<%= render @notes %>
  </tbody>
</table>
<br />
<p class="paginate"><%= will_paginate @notes, class: "pagination page-link btn" %><br /></p>
<%= link_to 'Crear una nota', new_note_of_book_path, class: 'btn btn-primary' %>
<BR><BR>
<%= link_to 'Volver a cuadernos', books_path, class: 'btn btn-primary' %>

app/views/notes/new.html.erb
<h3> Crear Nota </h3>

<%= render 'form' %>

<%= render 'codemirror' %>

app/views/notes/new_note_of_book.html.erb
<h3> Crear Nota para "<%= Book.find(@note.book_id).title %>" </h3>

<%= render 'form' %>

<%= render 'codemirror' %>

app/views/notes/show.html.erb
<h3>Contenido de "<%= @note.title %>" </h3>

<%= form_for @note do |f| %>
    <%= f.text_area :content, id: "form-note",  class: "codemirror-textarea form-control input-lg", placeholder: "Texto de la nota" %>
    <%- if @note.book_id.nil? %>
        <%= link_to 'Volver', notes_path, class: 'btn btn-primary' %>
    <% else %>
        <%= link_to 'Volver', notes_of_book_path(@note.book_id), class: 'btn btn-primary' %>
    <% end %>
    <% end %>

<script>
 CodeMirror.fromTextArea(document.getElementById("form-note"), {
 theme: "defualt",
 mode: "markdown",
 readOnly: true
})
</script>

app/views/notes/update.js.erb
<% if @note.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody tr#<%= @note.id %>').replaceWith(' <%= j render "note", note: @note %>');
  $('.alert').html("La nota se ha modificado con éxito").show();
  $('#form-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @note.errors.full_messages[0] %>');
<% end %>