config/routes.rb
Rails.application.routes.draw do
devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'home#index' 
resources :notes
resources :books
 # Agregados para hacer el pase desde Book a Note
get 'books/:book_id/notes', to: 'notes#index_notes_of_book', as: 'notes_of_book'
get 'books/:book_id/notes/:note_id', to: 'notes#show'
get 'books/:book_id/note', to: 'notes#new_note_of_book', as: 'new_note_of_book'
get 'notes/:id/download', to: 'notes#download', as: 'download'
get 'books/:id/download', to: 'books#download', as: 'download_zip'
get 'download', to: 'books#download_all', as: 'download_all'
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user, inverse_of: :books
    has_many :notes, dependent: :delete_all, inverse_of: :book

    validates :title, presence:true, length: { maximum: 255 }, format: { with: /\A(\w|(\w[\w\s]*\w))\z/, message: "no debe comenzar ni terminar con espacios en blanco"}
    validates :user_id, presence: true
    validates_uniqueness_of :title, scope: :user_id

##    No lo necesito mas, ya que ahora le pido los books al current_user
#    scope :books_for_user, -> (user_id){ where("user_id == ?", user_id)} 


    def self.search(user, params)
     books = self.where("user_id = #{user}")
     books =  where("title like ?", "%#{params[:search]}%") if params[:search]
     books
    end
    
    def to_s
        title
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    require 'rubygems'
    require 'zip'
    before_action :authenticate_user!
    before_action :set_book, only: [:show, :edit, :update, :destroy, :download ]
  
    def index
        @books = current_user.books.search(current_user.id, params ).paginate(page: params[:page], per_page: 6).order('created_at DESC')
#        @books = @books.sort_by {|book| book.title} # Ruby Sorting

    end 
       
    def new
        @book = current_user.books.new       
    end
    
    def create
        @book = current_user.books.new book_params
        @book.user_id = current_user.id
	@book.title = @book.title.gsub(/^\s*/,'').gsub(/\s*$/,'')
        @book.save        
        if @book.errors.empty?
           redirect_to books_path, notice: "Se creo el cuaderno '#{@book.title}'"
        end
    end

    def show
        redirect_to notes_of_book_path(@book.id)
    end
    
    def edit
    end
    
    def update

        @book.update book_params
        if @book.errors.empty?
           redirect_to books_path, notice: "Se actualizo el cuaderno '#{@book.title}'"
        end
    end
    
    def destroy
        titulo = @book.title
        @book.destroy
        redirect_to books_path, notice: "Se elimino el cuaderno '#{@book.title}'"
    end

    def download
        notes = current_user.notes.where("book_id == #{params[:id]}")
        Dir.mkdir("tmp/#{current_user.id}")
        Dir.mkdir("tmp/#{current_user.id}/#{@book.title}")
        zipfile = Zip::File.open("tmp/#{current_user.id}.zip", Zip::File::CREATE)
        zipfile.mkdir("#{@book.title}")
        notes.each do |n|
            File.write("tmp/#{current_user.id}/#{@book.title}/#{n.title}.html",n.markdown)
            zipfile.add("#{@book.title}/#{n.title}.html", "tmp/#{current_user.id}/#{@book.title}/#{n.title}.html" )
        end
        zipfile.close
        (Dir.new("tmp/#{current_user.id}/#{@book.title}")).children().map{|d| File.delete("tmp/#{current_user.id}/#{@book.title}/#{d}")}
        Dir.rmdir("tmp/#{current_user.id}/#{@book.title}")
        Dir.rmdir("tmp/#{current_user.id}/")
        send_data(File.read("tmp/#{current_user.id}.zip"), filename: "#{@book.title}.zip", type: 'application/zip' )
        File.delete("tmp/#{current_user.id}.zip")
    end

    def download_all
        books = current_user.books
        Dir.mkdir("tmp/#{current_user.id}")
        zipfile = Zip::File.open("tmp/#{current_user.id}.zip", Zip::File::CREATE)
        books.each do |b|
              Dir.mkdir("tmp/#{current_user.id}/#{b.title}")
              zipfile.mkdir("#{b.title}")
              notes = Note.where("user_id == #{current_user.id} AND book_id == #{b.id}")
              notes.each do |n|
                 File.write("tmp/#{current_user.id}/#{b.title}/#{n.title}.html",n.markdown)
                 zipfile.add("#{b.title}/#{n.title}.html", "tmp/#{current_user.id}/#{b.title}/#{n.title}.html" )
              end 
        end
        Dir.mkdir("tmp/#{current_user.id}global")
        notes = Note.where("user_id == #{current_user.id} AND book_id is null")        
        notes.each do |n|
             File.write("tmp/#{current_user.id}global/#{n.title}.html",n.markdown)
             zipfile.add("#{n.title}.html", "tmp/#{current_user.id}global/#{n.title}.html" )
        end
        zipfile.close
        (Dir.new("tmp/#{current_user.id}")).children().map{|d| (Dir.new("tmp/#{current_user.id}/#{d}")).children.map{|f| File.delete("tmp/#{current_user.id}/#{d}/#{f}")}}
        (Dir.new("tmp/#{current_user.id}")).children().map{|d| Dir.rmdir("tmp/#{current_user.id}/#{d}")}
        (Dir.new("tmp/#{current_user.id}global")).children().map{|f| File.delete("tmp/#{current_user.id}global/#{f}")}        
        Dir.rmdir("tmp/#{current_user.id}global")
        Dir.rmdir("tmp/#{current_user.id}")
        send_data(File.read("tmp/#{current_user.id}.zip"), filename: "#{current_user.name}.zip", type: 'application/zip' )
        File.delete("tmp/#{current_user.id}.zip")
    end

    private

    def book_params
        params.require(:book).permit(:title)
    end

    def set_book
        @book = current_user.books.find(params[:id])
        if @book.nil?
             render :'errors/403', status: :forbidden, :layout => false 
        end
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<tr id=<%= book.id %> >
<th scope="row"><%= link_to book.title, book_path(book.id) %></th>
<td><%= book.created_at.strftime("%d-%m-%Y   %H:%M") %></td>
<td><%= link_to  '<i class="fas fa-download"></i>'.html_safe, download_zip_path(book), target: "_blank" %></td>
<td><%= link_to  '<i class="fas fa-edit"></i>'.html_safe, edit_book_path(book) %></td>
<td><%= link_to '<i class="fas fa-trash"></i>'.html_safe, book, method: :delete, data: { confirm: 'Esta seguro?' } %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for @book, remote: true do |f| %>
    <%= f.label :titulo %>
    <%= f.text_field :title, class: "form-control input-lg", placeholder: "Nombre del cuaderno" %>
    <br />
    <%= f.submit 'Enviar', class: "btn btn-primary" %>
    <%= link_to 'Cancelar', books_path, class: 'btn btn-secundary' %>
<% end %>

app/views/books/create.js.erb
alert('<%= @book.errors.full_messages[0] %>');

app/views/books/edit.html.erb
<%= render 'form' %>

app/views/books/index.html.erb
<div class="form-group" align='right'>
<form >
 <input name='search' <%= @search %> >
 <button type=”submit”><i class="fas fa-search"></i></button>
</form>
</div>
<h2>Lista de cuadernos</h2>
<table class="table table-striped table-bordered" id="tbook">
  <thead>
  </thead>
  <tbody>
<%= render @books %>
  </tbody>
</table>
<p id="wp"><%= will_paginate @books, class: "pagination page-link btn" %></p>
<br />
<%= link_to 'Crear un cuaderno', new_book_path, class: 'btn btn-primary' %>

app/views/books/new.html.erb
<P> Crear un cuaderno </P>

<%= render 'form' %>

app/views/books/update.js.erb
alert('<%= @book.errors.full_messages[0] %>');