config/routes.rb
Rails.application.routes.draw do
devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'home#index' 
resources :notes
resources :books
 # Agregados para hacer el pase desde Book a Note
get 'books/:book_id/notes', to: 'notes#index_notes_of_book', as: 'notes_of_book'
get 'books/:book_id/notes/:note_id', to: 'notes#show'
get 'books/:book_id/note', to: 'notes#new_note_of_book', as: 'new_note_of_book'
get 'notes/:id/download', to: 'notes#download', as: 'download'
get 'books/:id/download', to: 'books#download', as: 'download_zip'
get 'download', to: 'books#download_all', as: 'download_all'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyNotes</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="<%= root_path %>lib/codemirror.css">
    <script src="<%= root_path %>lib/codemirror.js"></script>
    <script src="<%= root_path %>mode/markdown/markdown.js"></script>
    <link rel="stylesheet" href="<%= root_path %>theme/dracula.css">
    <script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://kit.fontawesome.com/627e804858.js" crossorigin="anonymous"></script>
  </head>

  <body>
<div>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    Ruby-Note
    </a>
    <div class="navbar-collapse" id="navbarSupportedContent">
      <%- if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
           <a class="nav-link dropdown-item" href=<%= notes_path %> >Notas sueltas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link dropdown-item" href=<%= books_path %> >Cuadernos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link dropdown-item" href=<%= download_all_path %> target="_blank"><i class="fas fa-download"></i></a>
        </li>
        </ul>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
          <%=link_to 'Editar', edit_user_registration_path %><br>
            <div class="dropdown-divider"></div>
          <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
          </div>
        </li>
      </ul>
    </div>
    <% else %>
      <ul class="nav navbar-nav ml-auto">
       <li class="nav-item">
        <a class="nav-link dropdown-item" href=<%= new_user_session_path %>>Iniciar</a>
       </li>
       <li class="nav-item">
        <a class="nav-link dropdown-item" href=<%= new_user_registration_path %> >Registrarme</a>
       </li>
       </ul>
    <% end %>    
  </div>
</nav>

    <p class="alert""><%= alert %></p>
    <p class="notice"><%= notice %></p>
<%= yield %>
   </div>
  </body>
</html>